language: python
python:
  - 2.6
  - 2.7
env:
  global:
    - DJANGO_SETTINGS_MODULE=twitter_tag.test_settings
  matrix:
    - DJANGO=1.3.7
    - DJANGO=1.4.5
matrix:
  include:
    - python: 3.3
      env: DJANGO=1.5 DJANGO_SETTINGS_MODULE=twitter_tag.test_settings
install:
  - pip install -q https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install nose coveralls
script:
  - coverage run --source=twitter_tag setup.py nosetests
branches:
  only:
    - dev
after_success:
  - coveralls